### PR TITLE
Adds exec and --bash-load

### PR DESCRIPTION
**Pull request by seth--**
Fixes the issue #9

Note that this is wrong:
`file1 skip exec`
And this is right:
`file1 skip`
`file1 exec`

Also, there are no tests for this

### CODE REVIEW

**Comment by justone** [comment]
Thank you for this pull request.

I ended up going a different way with `.bashrc.load`.  dfm now configures the loader if it exists.

I like the idea of your other patch (to add an 'exec' modifier).  I have one question.  Why did you use `-x` to test if the file is executable and `-O` to test if the file is owned?  According to the documentation, the former refers to EUID/EGID and the latter refers to the real UID.  Was this intentional?

**Comment by justone** [comment]
I forgot to link to the perl documentation.  It's here: http://perldoc.perl.org/5.10.1/functions/-X.html

**Comment by seth--** [comment]
It was unintentional, I just readed the documentation fast.
It should be -o and not -O

**Comment by justone** [comment]
The 'exec' modifier is now in master.

**Pull request closed without merging**
